### ISSUE TITLE
SpineOMatic Problem !!

### ISSUE THREAD

**Issue by LJRE15** [ExLibrisGroup/SpineOMatic#63] opened 2023-08-21 21:14 UTC
Hello,

We have a question about SpineOmatic that we are using in our library in order to print our labels.

Following message appears on the screen:

Error message:  ***** ERROR *****

Can't retrieve XML file. Error message: Error en el servidor remoto: (401) No autorizado.

 

Please your support with this problem. The program worked fine and then stopped working.

Thank you for your help!

**Comment by mgobat** [comment] 2023-08-21 21:32
@LJRE15, which version of SpineOMatic are you running? If not version 8.1.2, please update and try again. Let us know if it is still a problem. Thanks.

**Comment by LJRE15** [comment] 2023-08-28 15:00
Hello, 
We have recently installed the last version of SpineOMatic program (version 8.1.2), but have not been successful in resolve the error. Please, any information on how we can get this issue resolved? 
Thank you for your help.

**Comment by mgobat** [comment] 2023-08-28 16:14
@LJRE15, first check that the API key you are using in SpineOMatic has at least read-only authorization for BIbs. You can do this in the Ex Libris Developer Network. From the main page, click the "Build - My APIs" link, then "Manage Keys".

If your API key has the right permission:

I don't think this is specifically a SpineOMatic error. Rather, it may be something in your network/environment making the request to Alma fail authorization. To test this, do the following:

1. Go the "Alma Access" tab in SpineOMatic.
2. Copy the "ALMA URL" Field and paste it in a Notepad document.
3. Copy the "Method" field and paste it after the "ALMA URL" copied above in the Notepad document.
4. Replace the string "{item_barcode}" with a valid barcode for one of your items in the Notepad document. In my example below, my barcode is 02080.
5. Append "&apiKey=" after the item barcode in the Notepad document.
6. Finally, copy the "API Key" field value and paste it after the "&apiKey=" in the Notepad document.

You should end up with something that looks like this, but with your values for the barcode and api key:

`https://api-na.hosted.exlibrisgroup.com/almaws/v1/items?view=label&item_barcode=02080&apiKey=my_api_key
`

Copy the full URL from the Notepad document and paste it into the address bar of your web browser and hit the "Enter" key. If it works correctly, you should get a response of the XML that describes the item in Alma. It looks something like this:

`<item link="https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/991097980000541/holdings/224595110000541/items/234595100000541">
<bib_data link="https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/991097980000541">
<mms_id>991097980000541</mms_id>
<bib_suppress_from_publishing>false</bib_suppress_from_publishing>
<title>More than news : media power in public affairs /</title>
<author>MacKuen, Michael Bruce.</author>
<isbn>0803915764 (pbk.)</isbn>
<complete_edition/>
<network_numbers>
<network_number>(DE-604)0070447</network_number>
<network_number>(TrN)14681-train20072_c2db</network_number>
<network_number>81000183 //r83</network_number>
</network_numbers>
<place_of_publication>Beverly Hills, Calif. :</place_of_publication>
<date_of_publication>c1981.</date_of_publication>
<publisher_const>Sage Publications</publisher_const>
</bib_data>
<holding_data link="https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/991097980000541/holdings/224595110000541">
<holding_id>224595110000541</holding_id>
<holding_suppress_from_publishing>false</holding_suppress_from_publishing>
<calculated_suppress_from_publishing>false</calculated_suppress_from_publishing>
<permanent_call_number_type desc="Library of Congress classification">0</permanent_call_number_type>
<permanent_call_number>PN4888.P6 M3</permanent_call_number>
<call_number_type desc="Library of Congress classification">0</call_number_type>
<call_number>PN4888.P6 M3</call_number>
<accession_number/>
<copy_id>0</copy_id>
<in_temp_location>false</in_temp_location>
<temp_library desc="Main Library">MAIN</temp_library>
<temp_location desc="RES">Res</temp_location>
<temp_call_number_type/>
<temp_call_number/>
<temp_call_number_source/>
<temp_policy/>
</holding_data>
<item_data>
<pid>234595100000541</pid>
<barcode>02080</barcode>
<creation_date>2011-12-17Z</creation_date>
<modification_date>2011-12-17Z</modification_date>
<base_status desc="Item in place">1</base_status>
<awaiting_reshelving>false</awaiting_reshelving>
<physical_material_type desc="Book">BOOK</physical_material_type>
<policy/>
<provenance/>
<po_line/>
<is_magnetic>false</is_magnetic>
<year_of_issue/>
<enumeration_a/>
<enumeration_b/>
<enumeration_c/>
<enumeration_d/>
<enumeration_e/>
<enumeration_f/>
<enumeration_g/>
<enumeration_h/>
<chronology_i/>
<chronology_j/>
<chronology_k/>
<chronology_l/>
<chronology_m/>
<break_indicator/>
<pattern_type/>
<linking_number/>
<type_of_unit/>
<description/>
<receiving_operator/>
<process_type/>
<inventory_number/>
<inventory_price/>
<library desc="Main Library">MAIN</library>
<location desc="Main">main</location>
<alternative_call_number/>
<alternative_call_number_type/>
<storage_location_id/>
<pages/>
<pieces>1</pieces>
<public_note/>
<fulfillment_note/>
<internal_note_1/>
<internal_note_2/>
<internal_note_3/>
<statistics_note_1/>
<statistics_note_2/>
<statistics_note_3/>
<requested>false</requested>
<edition/>
<imprint>Beverly Hills, Calif. : Sage Publications, c1981.</imprint>
<language>eng</language>
<library_details>
<address>
<line1>1350 E Touhy Ave</line1>
<line2>200 E</line2>
<line3/>
<line4/>
<line5/>
<city>Des Plaines</city>
<country desc="United States">USA</country>
<email>andrea.hell@exlibrisgroup.com</email>
<phone>1 847-296-2200</phone>
<postal_code>60018</postal_code>
<state>IL</state>
</address>
</library_details>
<parsed_alt_call_number/>
<parsed_call_number>
<call_no>PN</call_no>
<call_no>4888</call_no>
<call_no>.P6</call_no>
<call_no>M3</call_no>
</parsed_call_number>
<title_abcnph>More than news : media power in public affairs / Michael Bruce MacKuen, Steven Lane Coombs ; foreword by Warren E. Miller.</title_abcnph>
<physical_condition/>
<committed_to_retain/>
<retention_reason/>
<retention_note/>
</item_data>
</item>
`

If you get anything else, then there most likely is something in your environment causing SpineOMatic to not function as expected. Please report back the response you get from this test in your web browser.

You may need to engage your IT team to track it down. Provide to them the URL you constructed by following the instructions above.

**Comment by LJRE15** [comment] 2023-08-28 21:42
Hello,
After follow the instructions, it's giving me this message to log in (attached file). Could you please give me the user and password?
![SpineOMatic-Error2](https://github.com/ExLibrisGroup/SpineOMatic/assets/142637138/c5082871-232b-41d8-be15-6ca9e9def32a)
Many thanks.

**Comment by mgobat** [comment] 2023-08-29 15:02
@LJRE15, it should not respond by asking for log in credentials. This means the issue is outside the SpineOMatic application. I suggest you open a ticket with Ex Libris Support. 

https://support.proquest.com/s/submit-a-case?language=en_US

**Closed** 2023-09-13 18:04 UTC
Labels: help wanted
